services:
  sql:
    image: mcr.microsoft.com/azure-sql-edge
    environment:
      ACCEPT_EULA: "1"
      MSSQL_SA_PASSWORD: "Password@1"
    ports:
      - "1433:1433"
    volumes:
      - sql-data:/var/opt/mssql
  n8n:
    image: n8nio/n8n
    container_name: n8n
    restart: always
    ports:
      - "443:5678"
    environment:
      - N8N_CORS_ALLOW_CREDENTIALS=true
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_SSL_CERT=/home/node/.n8n/certs/localhost.pem
      - N8N_SSL_KEY=/home/node/.n8n/certs/localhost-key.pem
      - N8N_PROTOCOL=https
      - N8N_CORS_ALLOW_ORIGIN=https://localhost:4200
      - N8N_CORS_ALLOW_METHODS=GET,POST,OPTIONS
      - N8N_CORS_ALLOW_HEADERS=Content-Type, Authorization
    volumes:
      - ./n8n_data:/home/node/.n8n
      - ./cert-n8n:/home/node/.n8n/certs


volumes:
  sql-data:
  n8n_data:
  cert-n8n:
